const observatoryData = {
  i: {
    id: "i",
    logo_filename: "logo.svg",
    thumb_filename: "thumb.jpeg",
    video_url_id: "288344114",
    sequence: {
      a: "a.jpg",
      b: "b.jpg",
      c: "c.jpg",
      d: "d.jpg",
      e: "e.jpg",
      f: "f.jpg",
    },
  },
  ii: {
    id: "ii",
    logo_filename: "logo.svg",
    thumb_filename: "thumb.jpeg",
    video_url_id: "288344114",
    sequence: {
      a: "a.jpg",
      b: "b.jpg",
      c: "c.jpg",
      d: "d.jpg",
      e: "e.jpg",
      f: "f.jpg",
    },
  },
  iii: {
    id: "iii",
    logo_filename: "logo.svg",
    thumb_filename: "thumb.jpeg",
    video_url_id: "288344114",
    sequence: {
      a: "a.jpg",
      b: "b.jpg",
      c: "c.jpg",
      d: "d.jpg",
      e: "e.jpg",
      f: "f.jpg",
    },
  },
  iv: {
    id: "iv",
    logo_file: "logo.svg",
    thumb_filename: "thumb.jpeg",
    video_url_id: "288344114",
    sequence: {
      a: "a.jpg",
      b: "b.jpg",
      c: "c.jpg",
      d: "d.jpg",
      e: "e.jpg",
      f: "f.jpg",
      g: "g.jpg",
    },
  },
  v: {
    id: "v",
    logo_filename: "logo.svg",
    thumb_filename: "thumb.jpeg",
    video_url_id: "288344114",
    sequence: {
      a: "a.jpg",
      b: "b.jpg",
      c: "c.jpg",
      d: "d.jpg",
      e: "e.jpg",
      f: "f.jpg",
      g: "g.jpg",
    },
  },
};

export default observatoryData;
